# Generated by Django 4.1.6 on 2023-03-16 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_name', models.CharField(max_length=64, verbose_name='板块名字')),
                ('plate_info', models.TextField(verbose_name='板块介绍')),
                ('plate_logo', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='板块logo')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='帖头')),
                ('content', models.TextField(verbose_name='帖子内容')),
                ('like', models.BigIntegerField(default=0, verbose_name='点赞数')),
                ('comment', models.DateTimeField(auto_now_add=True, null=True, verbose_name='发帖时间')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post/', verbose_name='帖子图片')),
                ('plate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.plate', verbose_name='板块id')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('age', models.IntegerField(default=18, verbose_name='年龄')),
                ('cell', models.CharField(blank=True, max_length=64, null=True, verbose_name='手机号')),
                ('city', models.CharField(blank=True, max_length=64, null=True, verbose_name='城市')),
                ('photo', models.ImageField(default='head/default.jpg', upload_to='head/', verbose_name='头像')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128, verbose_name='跟帖内容')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='跟帖时间')),
                ('more', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.reply', verbose_name='所跟帖数据ID')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.post', verbose_name='主帖ID')),
                ('replier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.userinfo', verbose_name='跟帖人')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.userinfo', verbose_name='发帖人id'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=128, null=True, verbose_name='信息内容')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='私信时间')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app01.userinfo', verbose_name='收信人id')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app01.userinfo', verbose_name='发信人id')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app01.userinfo', verbose_name='被关注人id')),
                ('follower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app01.userinfo', verbose_name='关注人id')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_er', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.userinfo', verbose_name='收藏人')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.post', verbose_name='帖子id')),
            ],
        ),
    ]
